config/routes.rb
##### AYTYCRM - Silvio Fernandes #####

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :ayty_dashboards do
  collection do
    post :add_block
    put :sort
  end
  member do
    post :add
  end
end

resources :ayty_access_levels

resources :ayty_roles

resources :ayty_managed_roles

resources :ayty_time_entry_types

post '/principal_memberships/ayty_replicate_memberships/ayty', :to => 'principal_memberships#ayty_replicate_memberships'
post '/users/ayty_replicate_memberships/ayty', :to => 'users#ayty_replicate_memberships'

get '/users/index_manager/ayty', :to => 'users#index_manager'
get '/users/index_managed/ayty', :to => 'users#index_managed'
get '/users/edit_manager/ayty', :to => 'users#edit_manager'
get '/users/edit_managed/ayty', :to => 'users#edit_managed'
post '/users/update_manager', :to => 'users#update_manager'
post '/users/update_managed', :to => 'users#update_managed'
delete '/users/delete_all_manager/:id', :to => 'users#delete_all_manager'
delete '/users/delete_all_managed/:id', :to => 'users#delete_all_managed'

get '/issues/ayty_template_notes/ayty', :to => 'issues#ayty_template_notes'

get '/journals/toggle_journal_ayty_hidden', :to => 'journals#toggle_journal_ayty_hidden'

get '/journals/toggle_journal_ayty_marked', :to => 'journals#toggle_journal_ayty_marked'

resources :ayty_issue_priorities do
  collection do
    post 'ayty_update_priorities'
    get 'ayty_render_responsible'
    get 'ayty_render_time_tracker_pendings'
    get 'ayty_render_watcher'
    get 'ayty_render_play'
  end
end

get '/time_trackers/add_status_transition', :to => 'time_trackers#add_status_transition'

get 'ayty_managements/has_pending/:issue_id', to: 'ayty_managements#has_pending', as: 'ayty_managements_has_pending'

get 'ayty_managements/has_checklist/:issue_id', to: 'ayty_managements#has_checklist', as: 'ayty_managements_has_checklist'

app/views/my/blocks/_timelog.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<h3>
  <%= link_to l(:label_spent_time), time_entries_path(:user_id => 'me') %>
  (<%= l(:label_last_n_days, 7) %>)
</h3>
<%
entries = timelog_items
entries_by_day = entries.group_by(&:spent_on)
%>

<% if User.current.allowed_to?(:log_time, nil, :global => true) %>
<div class="contextual">
  <%= link_to l(:button_log_time), new_time_entry_path, :class => "icon icon-add" %>
</div>
<% end %>

<div class="total-hours">
<p><%= l(:label_total_time) %>: <%= html_hours("%.2f" % entries.sum(&:hours).to_f) %></p>
</div>

<% if entries.any? %>
<table class="list time-entries">
<thead><tr>
<th><%= l(:label_activity) %></th>
<th><%= l(:label_project) %></th>
<th><%= l(:field_comments) %></th>
<th><%= l(:field_hours) %></th>

<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<th><%= l(:field_ayty_time_entry_type) %></th>

<th></th>
</tr></thead>
<tbody>
<% entries_by_day.keys.sort.reverse.each do |day| %>
    <tr class="odd">
    <td><strong><%= day == Date.today ? l(:label_today).titleize : format_date(day) %></strong></td>
    <!--
    ##### AYTYCRM - Silvio Fernandes #####
    # TICKET - 47145
    # Solicitado inclusao do tipo de apontamento
    # Aumentado o colspan de 2 para 3 para deixar tabela sem falhas
    -->
    <td colspan="3"></td>
    <td class="hours"><em><%= html_hours("%.2f" % entries_by_day[day].sum(&:hours).to_f) %></em></td>
    <td></td>
    </tr>
    <% entries_by_day[day].each do |entry| -%>
    <tr class="time-entry" style="border-bottom: 1px solid #f5f5f5;">
    <td class="activity"><%= entry.activity %></td>
    <td class="subject"><%= entry.project %> <%= h(' - ') + link_to_issue(entry.issue, :truncate => 50) if entry.issue %></td>
    <td class="comments"><%= entry.comments %></td>
    <td class="hours"><%= html_hours("%.2f" % entry.hours) %></td>

    <!-- ##### AYTYCRM - Silvio Fernandes ##### -->
    <td class="ayty_time_entry_type"><%= entry.ayty_time_entry_type %></td>

    <td class="buttons">
    <% if entry.editable_by?(@user) -%>
        <%= link_to image_tag('edit.png'), {:controller => 'timelog', :action => 'edit', :id => entry},
                                           :title => l(:button_edit) %>
        <%= link_to image_tag('delete.png'), {:controller => 'timelog', :action => 'destroy', :id => entry},
                                             :data => {:confirm => l(:text_are_you_sure)},
                                             :method => :delete,
                                             :title => l(:button_delete) %>
    <% end -%>
    </td>
    </tr>
    <% end -%>
<% end -%>
</tbody>
</table>
<% end %>