config/routes.rb
##### AYTYCRM - Silvio Fernandes #####

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :ayty_dashboards do
  collection do
    post :add_block
    put :sort
  end
  member do
    post :add
  end
end

resources :ayty_access_levels

resources :ayty_roles

resources :ayty_managed_roles

resources :ayty_time_entry_types

post '/principal_memberships/ayty_replicate_memberships/ayty', :to => 'principal_memberships#ayty_replicate_memberships'
post '/users/ayty_replicate_memberships/ayty', :to => 'users#ayty_replicate_memberships'

get '/users/index_manager/ayty', :to => 'users#index_manager'
get '/users/index_managed/ayty', :to => 'users#index_managed'
get '/users/edit_manager/ayty', :to => 'users#edit_manager'
get '/users/edit_managed/ayty', :to => 'users#edit_managed'
post '/users/update_manager', :to => 'users#update_manager'
post '/users/update_managed', :to => 'users#update_managed'
delete '/users/delete_all_manager/:id', :to => 'users#delete_all_manager'
delete '/users/delete_all_managed/:id', :to => 'users#delete_all_managed'

get '/issues/ayty_template_notes/ayty', :to => 'issues#ayty_template_notes'

get '/journals/toggle_journal_ayty_hidden', :to => 'journals#toggle_journal_ayty_hidden'

get '/journals/toggle_journal_ayty_marked', :to => 'journals#toggle_journal_ayty_marked'

resources :ayty_issue_priorities do
  collection do
    post 'ayty_update_priorities'
    get 'ayty_render_responsible'
    get 'ayty_render_time_tracker_pendings'
    get 'ayty_render_watcher'
    get 'ayty_render_play'
  end
end

get '/time_trackers/add_status_transition', :to => 'time_trackers#add_status_transition'

get 'ayty_managements/has_pending/:issue_id', to: 'ayty_managements#has_pending', as: 'ayty_managements_has_pending'

get 'ayty_managements/has_checklist/:issue_id', to: 'ayty_managements#has_checklist', as: 'ayty_managements_has_checklist'

app/views/issue_statuses/_ayty_attributes.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<p>
  <%= content_tag :label, l(:field_ayty_assignable_responsible) %>
  <%= hidden_field_tag "issue_status[ayty_assignable_responsible]", 0 %>
  <%= check_box_tag "issue_status[ayty_assignable_responsible]", 1, issue_status.ayty_assignable_responsible? %>
</p>

app/views/issue_statuses/index.html.erb
<div class="contextual">
<%= link_to l(:label_issue_status_new), new_issue_status_path, :class => 'icon icon-add' %>
<%= link_to(l(:label_update_issue_done_ratios), update_issue_done_ratio_issue_statuses_path, :class => 'icon icon-multiple', :method => 'post', :data => {:confirm => l(:text_are_you_sure)}) if Issue.use_status_for_done_ratio? %>
</div>

<h2><%=l(:label_issue_status_plural)%></h2>

<table class="list issue_statuses">
  <thead><tr>
  <th><%=l(:field_status)%></th>
  <% if Issue.use_status_for_done_ratio? %>
  <th><%=l(:field_done_ratio)%></th>
  <% end %>
  <th><%=l(:field_is_closed)%></th>

  <!-- # Tornar usuarios responsaveis como selecionaveis no "Atribuido" Para para qualquer usuario -->
  <th><%=l(:label_ayty_assignable_responsible_short)%></th>

  <th></th>
  </tr></thead>
  <tbody>
<% for status in @issue_statuses %>
  <tr class="<%= cycle("odd", "even") %>">
  <td class="name"><%= link_to status.name, edit_issue_status_path(status) %></td>
  <% if Issue.use_status_for_done_ratio? %>
  <td><%= status.default_done_ratio %></td>
  <% end %>
  <td><%= checked_image status.is_closed? %></td>

  <td><%= checked_image status.ayty_assignable_responsible? %></td>

  <td class="buttons">
    <%= reorder_handle(status) %>
    <%= delete_link issue_status_path(status) %>
  </td>
  </tr>
<% end %>
  </tbody>
</table>

<% html_title(l(:label_issue_status_plural)) -%>

<%= javascript_tag do %>
  $(function() { $("table.issue_statuses tbody").positionedItems(); });
<% end %>