config/routes.rb
##### AYTYCRM - Silvio Fernandes #####

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :ayty_dashboards do
  collection do
    post :add_block
    put :sort
  end
  member do
    post :add
  end
end

resources :ayty_access_levels

resources :ayty_roles

resources :ayty_managed_roles

resources :ayty_time_entry_types

post '/principal_memberships/ayty_replicate_memberships/ayty', :to => 'principal_memberships#ayty_replicate_memberships'
post '/users/ayty_replicate_memberships/ayty', :to => 'users#ayty_replicate_memberships'

get '/users/index_manager/ayty', :to => 'users#index_manager'
get '/users/index_managed/ayty', :to => 'users#index_managed'
get '/users/edit_manager/ayty', :to => 'users#edit_manager'
get '/users/edit_managed/ayty', :to => 'users#edit_managed'
post '/users/update_manager', :to => 'users#update_manager'
post '/users/update_managed', :to => 'users#update_managed'
delete '/users/delete_all_manager/:id', :to => 'users#delete_all_manager'
delete '/users/delete_all_managed/:id', :to => 'users#delete_all_managed'

get '/issues/ayty_template_notes/ayty', :to => 'issues#ayty_template_notes'

get '/journals/toggle_journal_ayty_hidden', :to => 'journals#toggle_journal_ayty_hidden'

get '/journals/toggle_journal_ayty_marked', :to => 'journals#toggle_journal_ayty_marked'

resources :ayty_issue_priorities do
  collection do
    post 'ayty_update_priorities'
    get 'ayty_render_responsible'
    get 'ayty_render_time_tracker_pendings'
    get 'ayty_render_watcher'
    get 'ayty_render_play'
  end
end

get '/time_trackers/add_status_transition', :to => 'time_trackers#add_status_transition'

get 'ayty_managements/has_pending/:issue_id', to: 'ayty_managements#has_pending', as: 'ayty_managements_has_pending'

get 'ayty_managements/has_checklist/:issue_id', to: 'ayty_managements#has_checklist', as: 'ayty_managements_has_checklist'

app/models/ayty_access_level.rb
# redMine - project management software
# Copyright (C) 2006-2007  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

##### AYTYCRM - Silvio Fernandes #####
class AytyAccessLevel < ActiveRecord::Base
  
  has_many :principals
  has_many :users
  has_many :journals
  has_many :attachments
  has_many :custom_fields

  attr_accessible :name, :level, :ayty_access
  
  ##### AYTYCRM - Silvio Fernandes #####
  # Relacionamento para Impedimentos
  # has_many :ayty_impediments
  
  validates_presence_of :name, :level
  validates_numericality_of :level

end

app/controllers/ayty_time_entry_types_controller.rb
##### AYTYCRM - Silvio Fernandes #####

class AytyTimeEntryTypesController < ApplicationController
  layout 'admin'
  
  before_filter :require_admin
  before_filter :find_ayty_time_entry_type, :only => [:edit, :update, :destroy]
  
  def index
    respond_to do |format|
      format.html {
        @ayty_time_entry_types_pages, @ayty_time_entry_types = paginate AytyTimeEntryType.sorted, :per_page => 25
        render :action => "index", :layout => false if request.xhr?
      }
    end
  end

  def new
    @ayty_time_entry_type = AytyTimeEntryType.new
  end

  def create
    @ayty_time_entry_type = AytyTimeEntryType.new(ayty_time_entry_type_params)
    if @ayty_time_entry_type.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to ayty_time_entry_types_path
      return
    end
    render :action => 'new'
  end

  def edit
  end

  def update
    if @ayty_time_entry_type.update_attributes(ayty_time_entry_type_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to ayty_time_entry_types_path(:page => params[:page])
    else
      render :action => 'edit'
    end
  end

  def ayty_time_entry_type_params
    params.require(:ayty_time_entry_type).permit(:name, :active, :position, :code, :client, :move_to)
  end

  def destroy

    @ayty_time_entry_type.destroy

    redirect_to ayty_time_entry_types_path
  end

  private

  def find_ayty_time_entry_type
    @ayty_time_entry_type = AytyTimeEntryType.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/helpers/ayty_time_entry_types_helper.rb
##### AYTYCRM - Silvio Fernandes #####
module AytyTimeEntryTypesHelper

  # metodo para retornar os Tipos de Apontamento
  def ayty_time_entry_type_options_for_select(time_entry=nil, issue=nil)

    if time_entry || issue
      issue_valid = time_entry.nil? ? issue : time_entry.issue
      if issue_valid
        solution_type = issue_valid.ayty_get_value_by_custom_field_name('Tipo de Solução', '')
        if issue_valid.qt_client_homologation_repproval.to_i > 0 || issue_valid.status_id == 23
          ayty_code_time_entry_type = "EXTERNO"
        else
          if  issue_valid.qt_reproof_internal.to_i > 0 ||
              issue_valid.qt_reproof_external.to_i > 0 ||
              issue_valid.qt_business_homologation_repproval.to_i > 0 ||
              issue_valid.qt_test_repproval.to_i > 0
            ayty_code_time_entry_type = "INTERNO"
          else
            if solution_type.to_s == "Problema Ayty"
              ayty_code_time_entry_type = "BUG"
            else
              if ["Tarefa","Melhoria","Problema Externo","Proposta Comercial"].include?(solution_type.to_s)
                ayty_code_time_entry_type = "NORMAL"
              end
            end
          end
        end
      end
    end

    collection = []
    collection << [[ "--- #{l(:actionview_instancetag_blank_option)} ---", '' ]]
    collection << (AytyTimeEntryType.sorted.collect { |e|
      if ayty_code_time_entry_type
        style = (e.code == ayty_code_time_entry_type) ? 'background: #EEE; color: red;' : "background: #FFF; color: #000;"
        [e.name, e.id, {:style => style}]
      else
        [e.name, e.id]
      end
    })

    selected_item = time_entry.ayty_time_entry_type_id if time_entry

    selected_item = AytyTimeEntryType.where(:code => ayty_code_time_entry_type).first.id if ayty_code_time_entry_type

    options_for_select(collection.reduce(:concat), selected_item)
  end

end

app/views/ayty_time_entry_types/_form.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<%= error_messages_for 'ayty_time_entry_type' %>

<div class="box tabular">

  <p><%= f.text_field :name, :required => true %></p>

  <p><%= f.check_box :active %></p>

  <p><%= f.text_field :code %></p>

  <p><%= f.check_box :client %></p>

</div>

app/views/ayty_time_entry_types/edit.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<%= title [l(:label_ayty_time_entry_types_plural), ayty_time_entry_types_path], @ayty_time_entry_type.name %>

<%= labelled_form_for @ayty_time_entry_type do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/ayty_time_entry_types/fields.html.erb
<%= title [l(:label_tracker_plural), trackers_path], l(:field_summary) %>

<% if @trackers.any? %>
  <%= form_tag fields_trackers_path do %>
    <div class="autoscroll">
    <table class="list">
    <thead>
      <tr>
        <th></th>
        <% @trackers.each do |tracker| %>
        <th>
          <%= tracker.name %>
          <%= link_to_function(image_tag('toggle_check.png'), "toggleCheckboxesBySelector('input.tracker-#{tracker.id}')",
                                                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}") %>
        </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr class="group open">
        <td colspan="<%= @trackers.size + 1 %>">
          <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
          <%= l(:field_core_fields) %>
        </td>
      </tr>
      <% Tracker::CORE_FIELDS.each do |field| %>
      <tr class="<%= cycle("odd", "even") %>">
        <td class="name">
          <%= link_to_function(image_tag('toggle_check.png'), "toggleCheckboxesBySelector('input.core-field-#{field}')",
                                                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}") %>
          <%= l("field_#{field}".sub(/_id$/, '')) %>
        </td>
        <% @trackers.each do |tracker| %>
        <td>
          <%= check_box_tag "trackers[#{tracker.id}][core_fields][]", field, tracker.core_fields.include?(field),
                            :class => "tracker-#{tracker.id} core-field-#{field}", :id => nil %>
        </td>
        <% end %>
      </tr>
      <% end %>
      <% if @custom_fields.any? %>
        <tr class="group open">
          <td colspan="<%= @trackers.size + 1 %>">
            <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
            <%= l(:label_custom_field_plural) %>
          </td>
        </tr>
        <% @custom_fields.each do |field| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td class="name">
            <%= link_to_function(image_tag('toggle_check.png'), "toggleCheckboxesBySelector('input.custom-field-#{field.id}')",
                                                                :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}") %>
            <%= field.name %>
          </td>
          <% @trackers.each do |tracker| %>
          <td>
            <%= check_box_tag "trackers[#{tracker.id}][custom_field_ids][]", field.id, tracker.custom_fields.include?(field),
                              :class => "tracker-#{tracker.id} custom-field-#{field.id}", :id => nil %>
          </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    </tbody>
    </table>
    </div>
    <p><%= submit_tag l(:button_save) %></p>
    <% @trackers.each do |tracker| %>
      <%= hidden_field_tag "trackers[#{tracker.id}][core_fields][]", '' %>
      <%= hidden_field_tag "trackers[#{tracker.id}][custom_field_ids][]", '' %>
    <% end %>
  <% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/ayty_time_entry_types/index.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<div class="contextual">
<%= link_to l(:label_ayty_time_entry_type_new), new_ayty_time_entry_type_path, :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_ayty_time_entry_types_plural)%></h2>

<table class="list">
  <thead><tr>
  <th><%=l(:label_ayty_time_entry_type)%></th>
  <th><%= l(:field_active) %></th>
  <th><%=l(:button_sort)%></th>
  <th></th>
  </tr></thead>
  <tbody>
<% for ayty_time_entry_type in @ayty_time_entry_types %>
  <tr class="<%= cycle("odd", "even") %>">
  <td class="name"><%= link_to ayty_time_entry_type.name, edit_ayty_time_entry_type_path(ayty_time_entry_type) %></td>
  <td class="tick"><%= checked_image ayty_time_entry_type.active? %></td>
  <td class="reorder">
    <%= reorder_links('ayty_time_entry_type', {:action => 'update', :id => ayty_time_entry_type, :page => params[:page]}, :put) %>
  </td>
  <td class="buttons">
    <%= delete_link ayty_time_entry_type_path(ayty_time_entry_type) %>
  </td>
  </tr>
<% end %>
  </tbody>
</table>

<p class="pagination"><%= pagination_links_full @ayty_time_entry_types_pages %></p>

<% html_title(l(:label_ayty_time_entry_types_plural)) -%>

app/views/ayty_time_entry_types/new.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<%= title [l(:label_ayty_time_entry_types_plural), ayty_time_entry_types_path], l(:label_ayty_time_entry_type_new) %>

<%= labelled_form_for @ayty_time_entry_type do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>