config/routes.rb
##### AYTYCRM - Silvio Fernandes #####

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :ayty_dashboards do
  collection do
    post :add_block
    put :sort
  end
  member do
    post :add
  end
end

resources :ayty_access_levels

resources :ayty_roles

resources :ayty_managed_roles

resources :ayty_time_entry_types

post '/principal_memberships/ayty_replicate_memberships/ayty', :to => 'principal_memberships#ayty_replicate_memberships'
post '/users/ayty_replicate_memberships/ayty', :to => 'users#ayty_replicate_memberships'

get '/users/index_manager/ayty', :to => 'users#index_manager'
get '/users/index_managed/ayty', :to => 'users#index_managed'
get '/users/edit_manager/ayty', :to => 'users#edit_manager'
get '/users/edit_managed/ayty', :to => 'users#edit_managed'
post '/users/update_manager', :to => 'users#update_manager'
post '/users/update_managed', :to => 'users#update_managed'
delete '/users/delete_all_manager/:id', :to => 'users#delete_all_manager'
delete '/users/delete_all_managed/:id', :to => 'users#delete_all_managed'

get '/issues/ayty_template_notes/ayty', :to => 'issues#ayty_template_notes'

get '/journals/toggle_journal_ayty_hidden', :to => 'journals#toggle_journal_ayty_hidden'

get '/journals/toggle_journal_ayty_marked', :to => 'journals#toggle_journal_ayty_marked'

resources :ayty_issue_priorities do
  collection do
    post 'ayty_update_priorities'
    get 'ayty_render_responsible'
    get 'ayty_render_time_tracker_pendings'
    get 'ayty_render_watcher'
    get 'ayty_render_play'
  end
end

get '/time_trackers/add_status_transition', :to => 'time_trackers#add_status_transition'

get 'ayty_managements/has_pending/:issue_id', to: 'ayty_managements#has_pending', as: 'ayty_managements_has_pending'

get 'ayty_managements/has_checklist/:issue_id', to: 'ayty_managements#has_checklist', as: 'ayty_managements_has_checklist'

app/models/ayty_role.rb
##### AYTYCRM - Silvio Fernandes #####

class AytyRole < ActiveRecord::Base
  
  # Relacionamento para Usuarios
  has_many :users
  
  validates_presence_of :name

  attr_accessible :name,
                  :group_name,
                  :active,
                  :allowed_view_dashboard,
                  :allowed_view_baseline,
                  :allowed_send_mail_time_entries,
                  :allowed_save_baseline,
                  :allowed_to_monitor_production,
                  :allowed_issues_highlights
    
end

app/controllers/ayty_roles_controller.rb
##### AYTYCRM - Silvio Fernandes #####

class AytyRolesController < ApplicationController
  layout 'admin'
  
  before_filter :require_admin
  
  def index
    @ayty_roles = AytyRole.order(:name).all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ayty_roles }
    end
  end

  def show
    @ayty_role = AytyRole.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ayty_role }
    end
  end

  def new
    @ayty_role = AytyRole.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ayty_role }
    end
  end

  def edit
    @ayty_role = AytyRole.find(params[:id])
  end

  def create
    @ayty_role = AytyRole.new(params[:ayty_role])

    respond_to do |format|
      if @ayty_role.save
        flash[:notice] = l(:notice_successful_create)
        format.html { redirect_to(ayty_roles_path) }
        format.xml  { render :xml => @ayty_role, :status => :created, :location => @ayty_role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ayty_role.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @ayty_role = AytyRole.find(params[:id])

    respond_to do |format|
      if @ayty_role.update_attributes(params[:ayty_role])
        flash[:notice] = l(:notice_successful_update)
        format.html { redirect_to(ayty_roles_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ayty_role.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @ayty_role = AytyRole.find(params[:id])
    @ayty_role.destroy

    respond_to do |format|
      format.html { redirect_to(ayty_roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ayty_roles_helper.rb
##### AYTYCRM - Silvio Fernandes #####
module AytyRolesHelper

  # Retorna Array com Cargos Ayty para um Select
  def ayty_roles_options_for_select
    AytyRole.order(:name).all.collect { |e| [e.name, e.id] }
  end

end

app/views/ayty_roles/_form.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->
<div class="box tabular">
    <p><%= f.text_field :name, :required => true %></p>
    <p><%= f.text_field :group_name, :label => :field_ayty_role_group_name %></p>
    <p><%= f.check_box :active %></p>
    <p><%= f.check_box :allowed_view_dashboard, :label => :field_ayty_role_allowed_view_dashboard %></p>
    <p><%= f.check_box :allowed_send_mail_time_entries, :label => :field_ayty_role_allowed_send_mail_time_entries %></p>
    <p><%= f.check_box :allowed_view_baseline, :label => :field_ayty_role_allowed_view_baseline %></p>
    <p><%= f.check_box :allowed_save_baseline, :label => :field_ayty_role_allowed_save_baseline %></p>
    <p><%= f.check_box :allowed_issues_highlights, :label => :field_ayty_role_allowed_issues_highlights %></p>
    <p><%= f.check_box :allowed_to_monitor_production, :label => :field_ayty_role_allowed_to_monitor_production %></p>
</div>

app/views/ayty_roles/edit.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->

<h2><%= link_to l(:label_ayty_roles_plural), ayty_roles_path %> &#187; <%= h(@ayty_role.name) %></h2>

<%= labelled_form_for :ayty_role, @ayty_role do |f| %>

    <%= error_messages_for @ayty_role %>

    <%= render :partial => 'form', :locals => { :f => f } %>

    <p><%= f.submit l(:button_save) %></p>

<% end %>

<% html_title(l(:label_ayty_roles_plural)) -%>

app/views/ayty_roles/index.html.erb
<!-- ##### AYTYCRM - Silvio Fernandes ##### -->

<div class="contextual">
    <%= link_to l(:label_ayty_role_new), new_ayty_role_path, :class => 'icon icon-add' %>
</div>

<h2><%= l(:label_ayty_roles_plural) %></h2>

<% if @ayty_roles.any? %>
<table class="list ayty_roles">
  <thead>
    <tr>
        <th><%=l(:field_name)%></th>
        <th><%=l(:field_ayty_role_group_name)%></th>
        <th><%=l(:field_active)%></th>
        <th><%=l(:field_ayty_role_allowed_view_dashboard)%></th>
        <th><%=l(:field_ayty_role_allowed_send_mail_time_entries)%></th>
        <th></th>
    </tr>
  </thead>
  <tbody>
<% @ayty_roles.each do |ayty_role| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td><%= link_to h(ayty_role.name), :action => 'edit', :id => ayty_role %></td>
    <td><%= h(ayty_role.group_name) %></td>
    <td><%= ayty_role.active ? l(:general_text_Yes):l(:general_text_No) %></td>
    <td><%= ayty_role.allowed_view_dashboard? ? l(:general_text_Yes):l(:general_text_No) %></td>
    <td><%= ayty_role.allowed_send_mail_time_entries ? l(:general_text_Yes):l(:general_text_No) %></td>
    <td class="buttons">
      <%= link_to l(:button_delete), {:action => 'destroy', :id => ayty_role}, :method => :delete, :class => 'icon icon-del', :data => {:confirm => l(:text_are_you_sure)} %>
    </td>
  </tr>
<% end %>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% html_title(l(:label_ayty_roles_plural)) -%>

app/views/ayty_roles/new.html.erb
<!--
##### AYTYCRM - Silvio Fernandes #####
# Cargos da Ayty
-->
<h2><%= link_to l(:label_ayty_roles_plural), ayty_roles_path %> &#187; <%= l(:label_ayty_role_new) %></h2>

<%= labelled_form_for :ayty_role, @ayty_role do |f| %>

    <%= error_messages_for @ayty_role %>

    <%= render :partial => 'form', :locals => { :f => f } %>

    <p><%= f.submit l(:button_create) %></p>

<% end %>

<% html_title(l(:label_ayty_roles_plural)) -%>